[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["Jihoon Son <jihoonson@apache.org>"]

[dependencies]
regex = "*"
regex_macros = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
llvm-sys = "*"

[dependencies.iron_llvm]
git = "https://github.com/jauhien/iron-llvm.git"
